# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/haolinmy/public_html/lms
#     - /bin/mkdir -p $DEPLOYPATH
#     - /bin/cp -rf ./* $DEPLOYPATH

---
deployment:
tasks:
- export DEPLOYPATH=/home/haolinmy/public_html/lms
- /bin/mkdir -p $DEPLOYPATH
- rsync -av --delete --exclude=.env --exclude=vendor --exclude=storage --exclude=bootstrap/cache ./ $DEPLOYPATH/