---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hoalinmy/public_html/LMS
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='storage/logs/*' ./ $DEPLOYPATH
    - php artisan optimize
